### ISSUE TITLE
Log-Cache consume all of the memory on vm during scaling out

### ISSUE THREAD

**Issue by Malsourie** [cloudfoundry/log-cache-release#89]
Hi all,
last week we decided to scale the whole loggregator out from 2 to 3 AZ and faced an issue on a large landscape. On that landscape we had 50 log-caches in total, 25 in AZ1 and 25 in AZ2. After scale out there will be 20 log-caches in each AZ1,2,3, so 60 in total. Our bosh update parameter max-in-flight is set to 2.

Bosh deploy process:

1. Creating missing log-caches: everything works fine
2. Deleting the extra log-caches in Z1: other nodes which route the logs to the deleted vms start to increase the memory consumption from around 60% -> 100%.
![image](https://user-images.githubusercontent.com/47302956/184318691-81de411b-7493-4652-acb5-ffd61bd8a82f.png)
3. Updating the first log-cache in Z1: the updated vm tried to connect to the nodes in Z3 and failed, the memory consumption from 0% -> 100%.
![image](https://user-images.githubusercontent.com/47302956/184318193-86b07423-b8d0-48d9-8b5b-a94ce2c0d4b4.png)

We ssh to the log-caches and figure out that the job log-cache ate all of the memory. Afterwards bosh agent cannot work and the instances became unresponsive agent state. We tried to iteratively execute bosh deploy with --fix flag to let bosh recreate those unresponsive vms and finally successfully updated all the log-caches nodes. Then all the log-caches work well and become calm down again.

During reproducing the memory exhausting, there are following findings: 
1. All of the node ip addresses are hard coded in [bpm.yml](https://github.com/cloudfoundry/log-cache-release/blob/0a94eaf172fe8b82b3d55ea2e6d200ce18d2684e/jobs/log-cache/templates/bpm.yml.erb#L39) file during bosh templating. And health of nodes will only be checked [once during starting of log-cache process by pinging the other nodes](https://github.com/cloudfoundry/log-cache/blob/526a0fd20d0308de00e5a3018047219428e31653/internal/cache/log_cache.go#L197). The cluster will not kick the unhealthy instance out when it is afterwards down.
2. Log-cache will allocate a [10,000 capacity one-to-one diode](https://github.com/cloudfoundry/log-cache/blob/526a0fd20d0308de00e5a3018047219428e31653/internal/routing/batched_ingress_client.go#L41) as batch-buffer for each peered node. It will cause problem during update since the cached envelops will be cached in those diodes until they are successfully routed to the peered nodes and these diodes are not limited by the parameter `MEMORY_LIMT_PERCENT`.

As a short term solution, we would like to patch the log-cache release: add the [bpm memory limit](https://bosh.io/docs/bpm/config/#limits-schema) in [bpm.yml](https://github.com/cloudfoundry/log-cache-release/blob/11fdbf4411d2e742334a3a626590e5143c860802/jobs/log-cache/templates/bpm.yml.erb#L50) to hard limit the memory consumption of log-cache job.

**Comment by Malsourie** [comment]
#90 <- I have created a PR for this issue.

**Comment by Benjamintf1** [comment]
Thanks for sharing. A few things on the general issue.

1) I suspect if we're leaking data, that the leaked data might be found in the grpc buffers rather than the diodes.

While we store data in these one-to-one diodes, they should be limited to 600,000 envelopes in total. Which, if we're talking about say, 5Kb envelopes on average, that's around 3GB per node. Are you using very small nodes for log-cache? Have you seen/instrumented log-cache to show this? 

2) I think while it would be nice to support larger topology changes easier, and be more resilient against large scale vm outages, I would suggest against doing such a large topology change with that low of a max_in_flight. It seems likely to lead to the same problems you have experienced. 

3) I'm concerned with the way that this is configured in the pr. Having it a static numerical limit I believe makes it difficult and problematic for operators to manage this configuration as it is not responsive to changes in vm size.

**Comment by Malsourie** [comment]
Hi @Benjamintf1, thanks for reviewing the topic.

1. Yes, grpc buffer could be also the part leaking data. The log-cache instance is vm with 60GB memory. But in the worst case the diode can consume 74 (nodes) * 3 GB/(per node) = 222 GB of memory, since log-cache will allocate one diode for each paired node.
2. Exactly, during normal update we set the max_in_flight to be only two instances. But this time we need to extend the log-cache to a new AZ, which will create a lot new instances in a new zone and cannot be avoidable. So we faced this issue for the first time.
3. I agree with you. The parameter `limits.memory` in bpm config only supports absolute value. I'm also thinking about the way defined for `MEMORY_LIMT_PERCENT`, which is configured in percentage. Do you think whether there is a way to template this value via calculation and analysing the deployed vm type?

**Comment by Benjamintf1** [comment]
I don't believe it's possible without changing bpm to support percentage memory limits in bpm.

**Comment by Benjamintf1** [comment]
I see your point about the variability of the log-cache diode sizes. 

I'm still not inclined to merge the pr as is, it's still very prone to operator error and doesn't do anything effective without setting it manually on a deployment. If it was set to some sensible limit by default, I think it would still be of limited use but maybe acceptable. I think the real solution to the problem is updating log-cache to take account of diodes and grpc buffers in it's pruning algorithms/memory accountancy.

**Comment by Malsourie** [comment]
Hi @Benjamintf1 , yes you are right. We should focus on the real cause of this issue. We decide to close this issue and will patch the log-cache in the future.
